### ISSUE TITLE
Busted Servos

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/Arduino_KHR-1#26] opened 2018-09-28 15:06 UTC
One of the hip servos were damaged and did not maintain torque during the demo at Party in the Park. This servo (and any other broken servos) need to be replaced.

- [x] replace servos.
- [x] realine and attach servos.
- [x] test all sevos

**Comment by halyngoc** [comment] 2018-10-06 02:14
Now there are 4 broken servos 👍

**Comment by jakechung42** [comment] 2018-10-06 05:29
since we know the issue is the servos now, gonna remove bug tag. Now just wait for the servos to be replace. I have to also test or the servos to make sure that not only those 4 are damages.

**Comment by williamVbrines** [comment] 2018-10-09 23:10
The servos that are broke are on. Check off when replaced.
[ ]CH3
[ ]CH6
[ ]CH9
[ ]Ch10

**Comment by williamVbrines** [comment] 2018-10-11 04:37
I tested all servos that are currently on KHR-1 with a custom program of mine all of them hold work.

**Comment by jakechung42** [comment] 2018-10-18 16:34
@williamVbrines did you reattached all the servos and rebuild KHR-1?

**Comment by williamVbrines** [comment] 2018-10-18 21:40
No is still don't have a working origin program that I can compile and load onto KHR1. I am waiting on ha for this to happen because I know she has a working program for doing this.

**Comment by jakechung42** [comment] 2018-10-18 21:46
Okay, we'll work on it tomorrow.

**Comment by jakechung42** [comment] 2018-10-18 21:47
opss clicked wrong button.

**Comment by williamVbrines** [comment] 2018-10-20 22:03
Someone close this issue.

**Closed** 2018-10-21 05:34 UTC
Labels: bug, hardware
